@startuml Архитектура_АгроТех_Фермы_v1.0

!include ../C4/C4_Component.puml

' === Участники ===
Person(оператор, "Оператор", "Мониторинг животных")
ContainerDb(бд, "База данных", "", "Хранит данные пользователей, животных, датчиков")
System_Ext(опсос, "Мобильный оператор", "SMS-оповещение")

System_Boundary(платформа, "АгроПром Х - Цифровая платформа фермы") {
	Container_Boundary(мониторинг_поголовья, "Трекер поголовья") {
		Component(аутентификация, "Аутентификации", "Обработка аутентификации")
		Component(авторизация, "Авторизации", "Проверка прав")
		Component(пользователи, "Пользователей", "Данные пользоветелей")
		Component(животные, "Животные", "Данные животных")
		Component(датчики, "Датчики", "Данные датчиков")
		Component(сообщения, "Сообщения", "Отправка сообщений")
		Component(данные, "Данные", "Взаимодействия с БД")
		Component(ui, "Интерфейс пользователя", "Взаимодействия с пользователем")
	}
}

' === Взаимосвязи ===
Rel(оператор, аутентификация, "Проходит аутентификацию")

' Аутентификация
Rel(аутентификация, сообщения, "Передает")
Rel(сообщения, опсос, "Отправляет")
Rel(опсос, оператор, "Доставляет")

' Авторизация
Rel(аутентификация, авторизация, "Использует")
Rel(авторизация, пользователи, "запрашивает")

' Взаимодействие с БД
Rel(пользователи, данные, "взаимодействует")
Rel(животные, данные, "взаимодействует")
Rel(датчики, данные, "взаимодействует")
Rel(данные, бд, "читает и записывает")

' Управление
Rel(оператор, ui, "Использует")
Rel(ui, животные, "Создает, изменяет, удаляет, просматривает")
Rel(ui, датчики, "Создает, изменяет, удаляет, просматривает")

@enduml