@startuml Архитектура_АгроТех_Фермы_v1.1

!include ../C4/C4_Context.puml

' === Участники ===
Person(оператор, "Оператор", "Мониторинг животных")
Person(техник, "Техник", "Управление устройствами")
Person(менеджер, "Менеджер", "Управление запасами")

System(устройства, "Агент EDGE", "Управление устройствами")
System(мониторинг, "Агент EDGE", "Мониторинг животных") 
System(сервер, "Центральный сервер фермы") 
System(платформа, "АгроПром Х - Цифровая платформа фермы") 

System_Ext(опсос, "Мобильный оператор", "SMS-оповещение")
System_Ext(web_api, "Web/Mobile API", "API для мобильного/веб-приложения")
System_Ext(data_api, "Выгрузка метрик", "Выгрузка метрик в другие системы")

' === Взаимосвязи ===
Rel(оператор, мониторинг, "Мониторит")
Rel(техник, устройства, "Управляет")
Rel(менеджер, платформа, "Планирует")

Rel(устройства, сервер, "Передает данные")
Rel(мониторинг, сервер, "Передает данные")

Rel(мониторинг, опсос, "Передает оповещения")
Rel(опсос, оператор, "Передает оповещения")

Rel(сервер, платформа, "Передает данные")

Rel(платформа, web_api, "Мониторинг и управление системой, планирование запасов")
Rel(платформа,data_api, "Выгрузка метрик")

@enduml

