@startuml Архитектура_АгроТех_Фермы_v1.0

!include ../C4/C4_Container.puml

' === Участники ===
Person(оператор, "Оператор", "Мониторинг животных")
Person(техник, "Техник", "Управление устройствами")
Person(менеджер, "Менеджер", "Управление запасами")

System_Boundary(платформа, "АгроПром Х - Цифровая платформа фермы") {
	Container_Boundary(устройства, "Управление устройствами") {
        Container(кормушки, "Кормушки", "Python", "Управление кормушками")
        Container(поилки, "Поилки", "Python", "Управление поилками")
        Container(фильтры, "Фильты воды", "Python", "Датчики фильтров")
		Container(scada, "SCADA система", "Ignition", "Управление устройствами")
	}

	Container_Boundary(мониторинг, "Мониторинг животных") {
		Container(видеомониторинг, "Мониторинг животных", "Python", "Камера+ИИ")
		Container(поголовье, "Индивидуальные датчики", "Python", "Идентификация, показатели состояния")
		Container(iot_шлюз, "IoT шлюз", "Node-RED", "Сбор данных")
		Container(tsdb, "База временных рядов", "TimescaleDB", "Данные датчиков")
		Container(мониторинг_поголовья, "Трекер поголовья", "Java", "Мониторинг поголовья")
	}	
	
    
	Container_Boundary(сервер, "Центральный сервер") {
		Container(брокер, "Брокер сообщений", "Kafka", "Шина данных")
		Container(хранилище, "Хранилище данных", "Click-House", "Структурированные данные")
		Container(метрики, "Аналитический модуль", "Python", "Метрики")
		Container(bi, "BI система", "Power BI", "Отчеты и визуализация")
    }    
	
}
System_Ext(опсос, "Мобильный оператор", "SMS-оповещение")
System_Ext(web_api, "Web/Mobile API", "API для мобильного/веб-приложения")
System_Ext(data_api, "Выгрузка метрик", "Выгрузка метрик в другие системы")

' === Взаимосвязи ===
Rel(оператор, мониторинг_поголовья, "Мониторит")
Rel(техник, scada, "Управляет")
Rel(менеджер, bi, "Планирует")

' Мониторинг
Rel(видеомониторинг, iot_шлюз, "Передает данные", "WiFi, LAN")
Rel(поголовье, iot_шлюз, "Передает данные", "LoRaWAN")
Rel(iot_шлюз, tsdb, "Сохраняет данные", "")
Rel(tsdb, мониторинг_поголовья, "Читает данные", "")

' Устройства
Rel(кормушки, scada, "Получает команды", "Modbus TCP")
Rel(поилки, scada, "Получает команды", "Modbus TCP")
Rel(фильтры, scada, "Передает данные", "LoRaWAN")

' Брокер
Rel(iot_шлюз, брокер, "Публикует данные", "Kafka")
Rel(scada, брокер, "Публикует данные", "OPC UA")

' Оповещение
Rel(iot_шлюз, опсос, "Передает оповещения")
Rel(опсос, оператор, "Передает оповещения")

' Сервер
Rel(брокер, хранилище, "Сохраняет данные", "ETL+Airflow")
Rel(хранилище, метрики, "Доступ к данным", "SQL")
Rel(метрики, bi, "Передает данные", "ODBC")

' Интеграции
Rel(метрики, web_api, "Мониторинг и управление сиcтемой, планирование запасов")
Rel(метрики,data_api, "Выгрузка метрик")

@enduml